server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lovecodeon/SpringCloud.git
          search-paths:
            - SpringCloud
          label: master
          skip-ssl-validation: true

    consul:
      discovery:
        heartbeat:
          enabled: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
      host: 43.138.40.184
      port: 8500